development:
  adapter: postgresql
  encoding: unicode
  database: hansel_dummy
  pool: 5
  username: hansel
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: hansel_dummy_test
  username: postgres
  pool: 5
